name: cpu_smoke_kerr_2mode
save: true

engine:
  sde:
    t0: 0.0
    t1: 1.0
    dt: 0.01
    n_traj: 2
    seed: 42
    ic:
      - ["1.0+0.0j", "0.0+0.0j"]

analyser:
  psd:
    modes: [0]
    kind: complex
    find_peaks: true

backend:
  numpy:
    float_dtype: float64

integrator:
  euler_maruyama: {}

model:
  kerr_2mode:
    omega_a: 0.0
    omega_b: [-0.001, -0.01, -0.1]
    chi: 0.01
    gamma_a: 0.5
    gamma_b: 1.8728
    g: 0.5
