name: vdp_2mode
save: true

engine:
  sde:
    # Time Domain
    t0: 0.0
    t1: 4800.0
    dt: 0.08

    # Ensemble
    n_traj: 100
    seed: 42
    ic:
      - ["800.0+0.0j", "0.0-800.0j"]

    # Adaptive
    adaptive: false
    save_stride: 1

    # Save Raw Trajectories
    keep_traj: false

analyser:
  psd:
    modes: [0]
    kind: complex
    find_peaks: true
  dist:
    modes: [0]
    range:
      - [-10.0, 10.0]
    bins: 100
    density: true
  pdist:
    modes: [0]
    bins: "auto"
    density: true

backend:
  cupy:
    float_dtype: float32
    device: cuda

integrator:
  euler_maruyama:
    method: euler

model:
  vdp_level3:
    omega_a: [0.001, 0.00125893, 0.00158489, 0.00199526, 0.00251189, 0.00316228,
              0.00398107, 0.00501187, 0.00630957, 0.00794328, 0.01, 0.01258925,
              0.01584893, 0.01995262, 0.02511886, 0.03162278, 0.03981072, 0.05011872,
              0.06309573, 0.07943282, 0.1]
    omega_b: 0.0
    gamma_a: 2.0
    gamma_b: 1.0
    Gamma: 0.0001
    g: 0.5
    D: 1.0
