- name: vdp_2mode_sim
  save: true
  engine:
    sde:
      t0: 0.0
      t1: 100.0
      dt: 0.1
      n_traj: 20
      seed: 42
      ic:
        - ["1.0+0.0j", "0.0+0.0j"]
      adaptive: false
      save_stride: 1
      keep_traj: false
  backend:
    numpy:
      float_dtype: float64
  integrator:
    srk:
      method: heun
  model:
    vdp_2mode:
      omega_a: [0.05, 0.1, 0.15]
      omega_b: 0.0
      gamma_a: 2.0
      gamma_b: 1.0
      Gamma: 0.00001
      g: 0.5
      D: 1.0
  analyser:
    psd:
      modes: [0, 1]
      kind: complex
      find_peaks: true
    dist:
      modes: [0, 1]
      bins: 20
      density: true
    pdist:
      modes: [0, 1]
      bins: 20
      density: true

- name: vdp_2mode_fit_mode0
  input: vdp_2mode_sim
  aggregate_input:
    on: params.omega_a
  save: true
  engine:
    sde:
      mode: analyze
  analyser:
    lorentz_fitter:
      scan_param: omega_a
      mode: 0
      export_dist: true
      export:
        - fit_results.csv
        - psd_merged.csv

- name: vdp_2mode_fit_mode1
  input: vdp_2mode_sim
  aggregate_input:
    on: params.omega_a
  save: true
  engine:
    sde:
      mode: analyze
  analyser:
    lorentz_fitter:
      scan_param: omega_a
      mode: 1
      export_dist: true
      export:
        - fit_results.csv
        - psd_merged.csv
