schema: qphase.workflow/2
id: kerr_3mode_cam
title: Kerr 3Mode Cam
collection: kerr_3mode
tags:
- kerr_3mode
jobs:
- name: kerr_3mode_cam
  save: true

  scan:
    combine: cartesian
    axes:
      omega_b:
        target: model.kerr_3mode.omega_b
        linspace: {start: -4.0, stop: 4.0, num: 201}
      gamma_c:
        target: model.kerr_3mode.gamma_c
        linspace: {start: 0.0, stop: 2.0, num: 201}

  engine:
    cam: {}

  plugins:
    backend:
      numpy:
        float_dtype: float64
    model:
      kerr_3mode:
        omega_a: 0.0
        omega_b: 0.0
        omega_c: 2.0
        chi: 0.001
        gamma_a: 1.0
        gamma_b: 0.5
        gamma_c: 0.5
        g_ab: 1.2
        g_ac: 1.0
    cam_solver:
      multistability:
        n_guesses: 50
        guess_bounds: auto
        distance_tolerance: 3.0
        retry_guesses: 200
        refine_guesses: 50
    cam_postprocessor:
      rayleigh_frequency: {}
      petermann_spectrum: {}
      jacobian_spectrum: {}
      physicality: {}
