"""Integrity tests for the frozen qphase_sde 1.x migration fixtures.

The fixtures under ``tests/fixtures/legacy_1x/`` pin the 1.x serialization
formats the 2.x migration tooling must read. They are one-shot migration
*inputs*, not a 2.x runtime format. These tests deliberately verify fixture
integrity only (files load, keys/shapes/dtypes match the frozen layout) — they
must never lock the legacy runtime API (``SDEResult.load``,
``SDEScanResult.load_dataset``) or require the frozen 1.x plugin catalog to
equal the current 2.x pyproject entry points, so that Phase 1/2 can delete the
old result classes without breaking the historical baseline.

The converter golden (``converter_expected.json``) is a manually reviewed
baseline: it is *not* regenerated by the tested converter (see
``_generate.py``), and any change to it requires an explicit review note in
the commit message.
"""

import ast
import json
import zipfile
from pathlib import Path

import numpy as np

from qphase_sde.contracts.migration import convert_analyser_config

FIXTURE_DIR = Path(__file__).resolve().parents[1] / "fixtures" / "legacy_1x"


def _npy_headers(npz_path: Path) -> dict[str, tuple[tuple[int, ...], np.dtype]]:
    """Read (shape, dtype) of every member of an npz archive from its header.

    Payloads are never read, so pickled object arrays are inspected without
    unpickling them.
    """
    headers: dict[str, tuple[tuple[int, ...], np.dtype]] = {}
    with zipfile.ZipFile(npz_path) as archive:
        for member_name in archive.namelist():
            with archive.open(member_name) as member:
                assert member.read(6) == b"\x93NUMPY"
                major = member.read(1)[0]
                member.read(1)  # minor version
                length_bytes = member.read(2 if major == 1 else 4)
                header_len = int.from_bytes(length_bytes, "little")
                header = ast.literal_eval(
                    member.read(header_len).decode("latin1")
                )
            descr = header["descr"]
            dtype = np.dtype(object) if descr == "|O" else np.dtype(descr)
            headers[member_name.removesuffix(".npy")] = (
                tuple(header["shape"]),
                dtype,
            )
    return headers


def test_fixtures_stay_small():
    """Migration fixtures must stay small enough to live in git."""
    oversized = [
        path.name
        for path in FIXTURE_DIR.rglob("*")
        if path.is_file() and path.stat().st_size > 256 * 1024
    ]
    assert oversized == []


def test_peak_fixtures_are_plain_arrays():
    """Single/double-peak fixtures carry plain arrays, no pickled objects."""
    for name in ("single_peak_psd", "double_peak_psd"):
        with np.load(FIXTURE_DIR / f"{name}.npz", allow_pickle=False) as npz:
            assert set(npz) >= {"frequency", "power", "sample_std"}
            assert npz["power"].shape == npz["frequency"].shape
            assert np.all(np.isfinite(npz["power"]))
            assert np.all(npz["power"] > 0)
    # The single-peak fixture peaks once; the double-peak fixture twice.
    with np.load(FIXTURE_DIR / "single_peak_psd.npz") as single:
        power = single["power"]
        assert int(np.argmax(power)) not in (0, power.size - 1)


def test_masked_trajectory_fixture_semantics():
    """The masked trajectory fixture carries valid lengths and NaN padding."""
    with np.load(FIXTURE_DIR / "masked_trajectory.npz", allow_pickle=False) as npz:
        data = npz["trajectories"]
        valid_length = npz["valid_length"]
        assert data.dtype == np.complex128
        assert data.shape[0] == valid_length.shape[0]
        for traj, length in enumerate(valid_length):
            assert np.all(np.isfinite(data[traj, :length]))
            assert np.all(np.isnan(data[traj, length:]))


def test_legacy_result_fixture_layout():
    """The frozen 1.x result npz keeps its keys, dtypes and shapes.

    Integrity is checked at the npy header level — the legacy runtime loader
    API and the pickled payloads are deliberately never exercised.
    """
    headers = _npy_headers(FIXTURE_DIR / "legacy_sde_result.npz")
    assert set(headers) == {
        "analysis",
        "data",
        "dt",
        "meta",
        "t0",
        "trajectory_meta",
    }
    assert headers["data"] == ((2, 32, 1), np.dtype(np.complex128))
    assert headers["dt"] == ((), np.dtype(np.float64))
    assert headers["t0"] == ((), np.dtype(np.float64))
    # meta/analysis are pickled-object scalars by 1.x design.
    for key in ("meta", "analysis", "trajectory_meta"):
        assert headers[key] == ((), np.dtype(object))


def test_sharded_scan_fixture_layout():
    """The per-point scan shards keep the frozen key/dtype/shape layout."""
    manifest = json.loads(
        (FIXTURE_DIR / "artifact_manifest_v2.json").read_text(encoding="utf-8")
    )
    shards = manifest["files"]
    assert len(shards) == manifest["shape"][0] == 3
    for shard in shards:
        headers = _npy_headers(FIXTURE_DIR / shard)
        assert set(headers) == {
            "analysis",
            "data",
            "dt",
            "meta",
            "t0",
            "trajectory_meta",
        }
        # n_traj_per_point=2, n_steps=16, n_modes=1 (see _generate.py).
        assert headers["data"] == ((2, 16, 1), np.dtype(np.complex128))


def test_artifact_manifest_v2_fixture_shape():
    """The artifact-manifest v2 sample carries the frozen v2 keys."""
    manifest = json.loads(
        (FIXTURE_DIR / "artifact_manifest_v2.json").read_text(encoding="utf-8")
    )
    assert manifest["schema_version"] == "2.0"
    assert set(manifest) >= {
        "result_type",
        "result_schema",
        "axes",
        "shape",
        "layout",
        "files",
        "loader",
    }
    for shard in manifest["files"]:
        assert (FIXTURE_DIR / shard).is_file()


def test_plugin_catalog_snapshot_is_valid_historical_evidence():
    """The frozen 1.x plugin catalog parses and holds dotted-path strings.

    This snapshot is historical migration evidence; it intentionally does NOT
    track the current 2.x pyproject entry points.
    """
    catalog = json.loads(
        (FIXTURE_DIR / "plugin_catalog.json").read_text(encoding="utf-8")
    )
    assert catalog, "catalog must not be empty"
    for package, entries in catalog.items():
        assert isinstance(package, str)
        for name, target in entries.items():
            assert "." in name, f"{package}:{name} is not namespaced"
            module, _, attr = target.partition(":")
            assert module and attr, f"{package}:{name} has no dotted target"


def test_converter_golden():
    """The one-shot converter reproduces the manually reviewed golden output.

    The golden is a frozen, human-reviewed baseline — not converter output
    re-blessed by the converter itself.
    """
    legacy = json.loads(
        (FIXTURE_DIR / "converter_legacy_input.json").read_text(encoding="utf-8")
    )
    expected = json.loads(
        (FIXTURE_DIR / "converter_expected.json").read_text(encoding="utf-8")
    )
    report = convert_analyser_config(legacy)
    assert report.converted == expected["converted"]
    assert report.diff == expected["diff"]
    assert report.unmapped == expected["unmapped"]
    assert report.needs_review == expected["needs_review"]
