schema: qphase.workflow/2
id: vdp_2mode_cam
title: Vdp 2Mode Cam
collection: vdp_2mode
tags:
- model:vdp_2mode
jobs:
- name: vdp_2mode_cam
  save: true

  scan:
    combine: cartesian
    axes:
      omega_a:
        target: model.vdp_2mode.omega_a
        linspace: {start: -0.3, stop: 0.3, num: 301}
      gamma_b:
        target: model.vdp_2mode.gamma_b
        linspace: {start: 0.2, stop: 1.1, num: 301}

  engine:
    cam: {}

  plugins:
    backend:
      numpy:
        float_dtype: float64
    model:
      vdp_2mode:
        omega_a: -0.3
        omega_b: 0.0
        gamma_a: 2.0
        gamma_b: 0.2
        Gamma: 0.0001
        g: 0.5
    cam_solver:
      multistability:
        n_guesses: 50
        guess_bounds: auto
        distance_tolerance: 3.0
        retry_guesses: 200
        refine_guesses: 50
    cam_postprocessor:
      rayleigh_frequency: {}
      petermann_spectrum: {}
      jacobian_spectrum: {}
      physicality: {}
