schema: qphase.workflow/2
id: kerr_full_3mode_omega_c_scaling_cam_positive
title: Kerr Full 3Mode Omega C Scaling Cam Positive
collection: kerr_full_3mode
tags:
- kerr_full_3mode
jobs:
- name: kerr_full_3mode_omega_c_scaling_cam_positive
  save: true

  engine:
    cam: {}

  plugins:
    backend:
      numpy:
        float_dtype: float64
    model:
      kerr_full_3mode:
        omega_a: 0.0
        omega_b: -0.8282592981043274
        omega_c: -0.998
        chi: 0.01
        gamma_a: 3.0
        gamma_b: 1.0
        gamma_c: 0.06381888082869307
        g_ab: 1.0
        g_ac: 0.2
        g_bc: 0.2
    cam_solver:
      continuation:
        parameter: omega_c
        start: -0.998
        stop: -0.95
        step: 0.05
        min_step: 1.0e-8
        max_step: 0.1
        max_steps: 5000
        corrector_iterations: 30
        tolerance: 1.0e-10
        initial_guess:
        - ["2.6942930856447886+0.0j", "1.7349426718923573-3.053912069781892j", "-20.394580232988556-1.187637793426454j"]
        - ["1.7349426718923573+3.053912069781892j", "6.122722449574776+0.0j", "-14.47646849048136-29.3263664728464j"]
        - ["-20.394580232988556+1.187637793426454j", "-14.47646849048136+29.3263664728464j", "190.75377236357744+0.0j"]
    cam_postprocessor:
      rayleigh_frequency: {}
      petermann_spectrum: {}
      jacobian_spectrum: {}
      physicality: {}
