"""Generate the reviewed fpgen public API snapshot used by qphase_cam."""

from __future__ import annotations

import argparse
import dataclasses
import inspect
import subprocess
from pathlib import Path
from typing import Any

import fpgen

PUBLIC_TYPES = (
    "CovarianceDynamics",
    "MomentDynamicsSpec",
    "CompiledMomentDynamics",
    "LinearReductionCandidate",
    "ReductionSearchResult",
    "LinearReductionPlan",
    "MaterializedReduction",
    "MaterializationFailure",
    "RejectedPartition",
)
METHODS = (
    ("CovarianceDynamics", "to_model_spec"),
    ("CovarianceDynamics", "jacobian"),
    ("CovarianceDynamics", "directional"),
    ("CovarianceDynamics", "search_linear_reductions"),
    ("CovarianceDynamics", "linear_reduce"),
    ("MomentDynamicsSpec", "compile_numpy"),
    ("ReductionSearchResult", "manifest"),
    ("LinearReductionPlan", "materialize"),
)


def _git(source_root: Path, *args: str) -> str:
    completed = subprocess.run(
        ["git", "-C", str(source_root), *args],
        check=False,
        capture_output=True,
        text=True,
    )
    return completed.stdout.strip() if completed.returncode == 0 else "unavailable"


def _fields(value: Any) -> str:
    if not dataclasses.is_dataclass(value):
        return "not a dataclass"
    return ", ".join(item.name for item in dataclasses.fields(value))


def render() -> str:
    package_dir = Path(fpgen.__file__).resolve().parent
    source_root = package_dir.parent
    revision = _git(source_root, "rev-parse", "HEAD")
    dirty = bool(_git(source_root, "status", "--porcelain"))
    lines = [
        "# fpgen API Snapshot",
        "",
        "Generated by `tools/generate_fpgen_api_snapshot.py`.",
        "",
        f"- source: `{source_root}`",
        f"- git revision: `{revision}`",
        f"- dirty worktree: `{str(dirty).lower()}`",
        f"- package version: `{fpgen.__version__}`",
        f"- model schema: `{fpgen.MODEL_SCHEMA_VERSION}`",
        f"- moment API: `{fpgen.MOMENT_DYNAMICS_API_VERSION}`",
        f"- reduction API: `{fpgen.REDUCTION_API_VERSION}`",
        "",
        "## Required Public Exports",
        "",
    ]
    exported = set(fpgen.__all__)
    lines.extend(
        f"- `{name}`: {'present' if name in exported else 'MISSING'}"
        for name in PUBLIC_TYPES
    )
    lines.extend(["", "## Signatures", ""])
    for type_name, method_name in METHODS:
        method = getattr(getattr(fpgen, type_name), method_name)
        lines.append(f"- `{type_name}.{method_name}{inspect.signature(method)}`")
    lines.extend(["", "## Dataclass Fields", ""])
    for name in PUBLIC_TYPES:
        lines.append(f"- `{name}`: `{_fields(getattr(fpgen, name))}`")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("reports/fpgen_api_snapshot.md"),
    )
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    content = render()
    if args.check:
        if (
            not args.output.exists()
            or args.output.read_text(encoding="utf-8") != content
        ):
            raise SystemExit(f"fpgen API snapshot is stale: {args.output}")
        return 0
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(content, encoding="utf-8")
    print(args.output)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
